### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({
    'color': ['red','blue','red','green','green','blue','blue','green']
})

In [3]:
df.head()

   color
0    red
1   blue
2    red
3  green
4  green

In [4]:
encoder = OneHotEncoder()

In [7]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [9]:
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoded_df.astype(int)

   color_blue  color_green  color_red
0           0            0          1
1           1            0          0
2           0            0          1
3           0            1          0
4           0            1          0
5           1            0          0
6           1            0          0
7           0            1          0

In [ ]:
encoder.transform([['blue']])

In [13]:
df_encoded = pd.get_dummies(df['color'])
df_encoded.astype(int)

   blue  green  red
0     0      0    1
1     1      0    0
2     0      0    1
3     0      1    0
4     0      1    0
5     1      0    0
6     1      0    0
7     0      1    0

In [15]:
pd.concat([df,encoded_df.astype(int)],axis=1)

   color  color_blue  color_green  color_red
0    red           0            0          1
1   blue           1            0          0
2    red           0            0          1
3  green           0            1          0
4  green           0            1          0
5   blue           1            0          0
6   blue           1            0          0
7  green           0            1          0

In [16]:
import seaborn as sns

df = sns.load_dataset('tips')

In [17]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [20]:
encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[['sex','smoker','day','time']]).toarray()

In [24]:
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out()).astype(int)
encoded_df.head()

   sex_Female  sex_Male  smoker_No  ...  day_Thur  time_Dinner  time_Lunch
0           1         0          1  ...         0            1           0
1           0         1          1  ...         0            1           0
2           0         1          1  ...         0            1           0
3           0         1          1  ...         0            1           0
4           1         0          1  ...         0            1           0

[5 rows x 10 columns]

In [25]:
final_df = pd.concat([df,encoded_df],axis=1)

In [26]:
final_df

     total_bill   tip     sex  ... day_Thur time_Dinner time_Lunch
0         16.99  1.01  Female  ...        0           1          0
1         10.34  1.66    Male  ...        0           1          0
2         21.01  3.50    Male  ...        0           1          0
3         23.68  3.31    Male  ...        0           1          0
4         24.59  3.61  Female  ...        0           1          0
..          ...   ...     ...  ...      ...         ...        ...
239       29.03  5.92    Male  ...        0           1          0
240       27.18  2.00  Female  ...        0           1          0
241       22.67  2.00    Male  ...        0           1          0
242       17.82  1.75    Male  ...        0           1          0
243       18.78  3.00  Female  ...        1           1          0

[244 rows x 17 columns]