## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [2]:
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [5]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [6]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [7]:
df['city_encoded'] = df['city'].map(mean_price)

In [8]:
df.head()

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0

In [9]:
import seaborn as sns

df = sns.load_dataset('tips')

In [11]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
mean_time = df.groupby('time')['total_bill'].mean()

In [13]:
mean_time

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [14]:
df['time_encoded'] = df['time'].map(mean_time)

In [18]:
df[df['time']=='Lunch']

     total_bill   tip     sex smoker   day   time  size time_encoded
77        27.20  4.00    Male     No  Thur  Lunch     4    17.168676
78        22.76  3.00    Male     No  Thur  Lunch     2    17.168676
79        17.29  2.71    Male     No  Thur  Lunch     2    17.168676
80        19.44  3.00    Male    Yes  Thur  Lunch     2    17.168676
81        16.66  3.40    Male     No  Thur  Lunch     2    17.168676
..          ...   ...     ...    ...   ...    ...   ...          ...
222        8.58  1.92    Male    Yes   Fri  Lunch     1    17.168676
223       15.98  3.00  Female     No   Fri  Lunch     3    17.168676
224       13.42  1.58    Male    Yes   Fri  Lunch     2    17.168676
225       16.27  2.50  Female    Yes   Fri  Lunch     2    17.168676
226       10.09  2.00  Female    Yes   Fri  Lunch     2    17.168676

[68 rows x 8 columns]

In [20]:
df[['time','time_encoded','total_bill','sex']].iloc[77:]

       time time_encoded  total_bill     sex
77    Lunch    17.168676       27.20    Male
78    Lunch    17.168676       22.76    Male
79    Lunch    17.168676       17.29    Male
80    Lunch    17.168676       19.44    Male
81    Lunch    17.168676       16.66    Male
..      ...          ...         ...     ...
239  Dinner    20.797159       29.03    Male
240  Dinner    20.797159       27.18  Female
241  Dinner    20.797159       22.67    Male
242  Dinner    20.797159       17.82    Male
243  Dinner    20.797159       18.78  Female

[167 rows x 4 columns]